name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Harbor
      uses: docker/login-action@v2.1.0
      with:
        registry: demo.goharbor.io
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        target: development
        file: ./Dockerfile
        push: true
        tags: demo.goharbor.io/${{ secrets.HARBOR_USERNAME }}/demo:latest
